### ISSUE TITLE
Error when building for iOS: error: 'asl_log' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3) [-Werror,-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by gustavottc** [godotengine/godot-mono-builds#17]
**OS/device including version:**
OS: Mac OS X 10.15.7
SDK: iPhoneOS14.0
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#language-and-runtime

**Issue description:**
I'm currently trying to build this using GitHub Actions, this mac-os image is with the latest software versions: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1403642388?check_suite_focus=true

**Comment by neikeq** [comment]
Did you run `patch_mono.py` before building? We have a patch for this error: https://github.com/godotengine/godot-mono-builds/blob/master/files/patches/mono_ios_asl_log_deprecated.diff. I didn't test it with latest mono though.

**Comment by gustavottc** [comment]
I just did this, but now another error has appeared: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1406546415?check_suite_focus=true

ld: warning: -undefined dynamic_lookup is deprecated on iOS
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make [4]: *** [libmonosgen-2.0.la] Error 1
make [3]: *** [all] Error 2
make [2]: *** [all-recursive] Error 1
make [1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make': make -j1 -C / Users / runner / mono-configs / ios-arm64-release
'make' exited with error code: 2
Error: Process completed with exit code 1.

**Comment by neikeq** [comment]
You can run `ios.py` with the environment variable `DISABLE_NO_WEAK_IMPORTS=1`. We're removing that option entirely soon.

**Comment by gustavottc** [comment]
Another error: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1408079268?check_suite_focus=true

/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/mono/support/sys-uio.c:99:8: error: implicit declaration of function 'preadv' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        res = preadv (dirfd, v, iovcnt, (off_t) off);
              ^
/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/mono/support/sys-uio.c:119:8: error: implicit declaration of function 'pwritev' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        res = pwritev (dirfd, v, iovcnt, (off_t) off);
              ^
2 errors generated.
make[2]: *** [sys-uio.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
'make' exited with error code: 2
Running command 'make': make -j1 -C /Users/runner/mono-configs/ios-arm64-release

**Comment by akien-mga** [comment]
Fixed by #15. Note that you should use the same Mono version as this PR (6.12.0.111 - or a later 6.12 tag should work too).

**Comment by gustavottc** [comment]
Ty so much, working fine now: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1412025183?check_suite_focus=true
