### ISSUE TITLE
error: the following arguments are required: --mono-sources

### ISSUE THREAD

**Issue by LaurentOngaro** [godotengine/godot-mono-builds#2]
I've got an error when I try to pass "--mono-sources", "--install-dir" or "--configure-dir" argument to the desktop.py script.

This is the command I've tested in a terminal:
`./desktop.py linux configure --mono-sources="/mnt/R/Apps_Sources/mono" --target=i686 --target=x86_64` 
OR
`./desktop.py linux make --mono-sources="/mnt/R/Apps_Sources/mono" --target=i686 --target=x86_64` 
and it produces the following error:
> desktop.py: error: the following arguments are required: --mono-sources

The error is thrown by the line #215 of the desktop.py file

I've tried to debug the script by myself, without success:

To check the arguments, I've added, the following line: 
`print(raw_args)` 
at line #214 

This is the output of the print command:
> ['linux', 'configure', '--mono-sources=/mnt/R/Apps_Sources/mono', '--target=i686', '--target=x86_64']

so the argument "--mono-sources" seems to be well transmitted, but it's not detected.

note that the command:
`export MONO_SOURCE_ROOT=/mnt/R/Apps_Sources/mono;./desktop.py linux configure --target=i686 --target=x86_64`
runs well,but 
`export MONO_SOURCE_ROOT=/mnt/R/Apps_Sources/mono;./desktop.py linux configure --target=i686 --target=x86_64 --install-dir=/tmp`
fails with the similar error:
> desktop.py: error: unrecognized arguments: --install-dir=/tmp

Perhaps it's an issue due to the argument containing an "-" ?

I use Python 3.8.1 on Arch linux x64

Thanks for your work and your help

**Comment by LaurentOngaro** [comment]
After a long testing time I've found an explanation to my issue.
The arguments must be placed in a specific order.

This one fails, with the 'unrecognized arguments' error
`python ./desktop.py linux configure --mono-sources=/mnt/R/Apps_Sources/mono --target=i686 --target=x86_64`

but this one works:
`python ./desktop.py --mono-sources=/mnt/R/Apps_Sources/mono linux configure --target=i686 --target=x86_64`

It might be a good idea to specify the correct order for the parameters in the Readme file.

**Comment by neikeq** [comment]
Fixed by 9670946cf513a329b1daa868a20292627595ae26. Check the README for the new commands.
