### ISSUE TITLE
Error when running ./patch_mono.py and ./patch_emscripten.py Any suggestions?

### ISSUE THREAD

**Issue by iplusMario** [godotengine/godot-mono-builds#9]
**python3 ./patch_mono.py**
error:
Running: patch -N -p1 < /home/sa/godot-mono-builds/files/patches/fix-mono-android-tkill.diff
patching file mono/metadata/threads.c
Hunk #1 FAILED at 77.
1 out of 1 hunk FAILED -- saving rejects to file mono/metadata/threads.c.rej
patching file mono/utils/mono-threads-posix.c
Hunk #1 FAILED at 31.
1 out of 1 hunk FAILED -- saving rejects to file mono/utils/mono-threads-posix.c.rej
patch exited with error code: 1

**python3 ./patch_emscripten.py**
error:
Running: patch -N -p1 < /home/sa/mono/sdks/builds/fix-emscripten-8511.diff
bash: /home/sa/mono/sdks/builds/fix-emscripten-8511.diff: No such file or directory
patch exited with error code: 1

**Comment by ksvslk** [comment]
+1

**Comment by iplusMario** [comment]
i think i found the problem you need to build mono sdks first (I am currently building so it's not confirmed yet) 
Flollow the instructions on "https://github.com/mono/mono/tree/master/sdks"
read sections "Setup" and "Building for XA/XI/XM and WebAssembly"

**Comment by neikeq** [comment]
No, you don't need to build these SDKs yourself.
The patch may not work with older or newer versions of the files. What is the Mono commit hash?

**Comment by iplusMario** [comment]
Aha ok so not all versions are compatible. I have downloaded latest godot-mono-builds and latest mono.
So wich version of mono should i download to use it with latest godot-mono-build?

I got this hash 4835e294701c9aa2aa0b49194bb3ae7499e11b6f from running "git rev-parse HEAD" on "mono" directory

**Comment by iplusMario** [comment]
> No, you don't need to build these SDKs yourself.
> The patch may not work with older or newer versions of the files. What is the Mono commit hash?

Aha ok so not all versions are compatible. I have downloaded latest godot-mono-builds and latest mono.
So wich version of mono should i download to use it with latest godot-mono-build?

I got this hash 4835e294701c9aa2aa0b49194bb3ae7499e11b6f from running "git rev-parse HEAD" on "mono" directory

**Comment by neikeq** [comment]
Right now the safest one would be the one the CI builds are using: https://github.com/godotengine/godot-mono-builds/blob/331653f9c32a4cffcac44197a87ba81baf289f2b/.github/workflows/build.yml#L30

That would be: https://github.com/mono/mono/commit/1d0d939dc30a5b56f478bc9f097cab146276b9af

**Comment by iplusMario** [comment]
Ok thank you now i checked out mono-6.8.0.123
the patch_mono works but partc_emscripten fails with following error is this normal?

python3 ./patch_emscripten.py --mono-source=$HOME/mono
Running: patch -N -p1 < /home/sa/mono/sdks/builds/fix-emscripten-8511.diff
patching file src/support.js
Hunk #1 succeeded at 296 with fuzz 1 (offset -6 lines).
patching file tests/test_browser.py
Hunk #1 succeeded at 2455 (offset 47 lines).
Running: patch -N -p1 < /home/sa/mono/sdks/builds/emscripten-pr-8457.diff
patching file emcc.py
Hunk #1 FAILED at 890.
Hunk #2 FAILED at 915.
Hunk #3 FAILED at 1838.
3 out of 3 hunks FAILED -- saving rejects to file emcc.py.rej
patch exited with error code: 1

**Comment by neikeq** [comment]
This one is important not only for the patch to work, because there were issues building Mono with some emscripten versions.

Right now the CI builds use 1.38.47-upstream: https://github.com/godotengine/godot-mono-builds/blob/331653f9c32a4cffcac44197a87ba81baf289f2b/.github/workflows/build.yml#L32
This is what the official builds use as well.
